### ISSUE TITLE
Using subschema.js with ASP.NET MVC and ReactJS.NET

### ISSUE THREAD

**Issue by martosource** [subschema/subschema#10]
I am trying to use the prebuild subschema.js with ASP.NET MVC 5 and ReactJS.NET (react-0.13.1). 

Receive the following error:
Uncaught TypeError: Cannot read property 'createClass' of undefined @ Editor.js:58
	t @ bootstrap cc196f695d536e0fcd55:19
	(anonymous function) @ NestedMixin.js:3
	t @ bootstrap cc196f695d536e0fcd55:19
	t @ form.js:2
	t @ bootstrap cc196f695d536e0fcd55:19
	(anonymous function) @ index.js:1
	t @ bootstrap cc196f695d536e0fcd55:19
	(anonymous function) @ index.jsx:1
	t @ bootstrap cc196f695d536e0fcd55:19
	(anonymous function) @ bootstrap cc196f695d536e0fcd55:39
	(anonymous function) @ bootstrap cc196f695d536e0fcd55:39
	n.(anonymous function).exports @ universalModuleDefinition:9
	(anonymous function) @ universalModuleDefinition:9

**Comment by jspears** [comment]
Can you share your schema? My guess is there us a typo with the name of an
type.  Try remoiving fields to narrow it down.

**Comment by trustorm** [comment]
The error is reported without any calls to subschema.

**Comment by trustorm** [comment]
My current test setup in a ASP.NET MVC view
```javascript
<script src="http://fb.me/react-0.13.1.js"></script>
    <script src="/Scripts/subschema/subschema.js"></script>
    <script src="/Scripts/forms.jsx"></script>
    <script>
        React.render(
            React.createElement(MyForms),
            document.getElementById("content")
        );
    </script>
```
forms.jsx - compiled via ReactJS.NET
```javascript
class MyForms extends React.Component {

render() {
    return (
      	  <div>Hello</div>
    )}
}
```

**Comment by jspears** [comment]
Probably because react is compiled into subscema. That is not smart I will
fix it, can you remove the react import and let me know if you still get
the error?

**Comment by trustorm** [comment]
@jspears Yeah, still get the same error without the react import. Tried with the subschema-0.9.3

**Comment by trustorm** [comment]
@jspears I rebuild subschema.js with output.libraryTarget: 'var' and it is now working.

**Comment by topgun743** [comment]
So having read this post, should I assume that SubSchema can be used with Asp.Net MVC without using Node.js? Am I right?
If yes then an example Asp.Net MVC project using SubSchema coupled with React, will be like an unexpected rain the desert :)

**Comment by jspears** [comment]
You can, I don't know much about Asp, but I assume it can include JS.   It won't work isomorphically (i.e. server side) unless asp has some javascript magic in it.

**Comment by martosource** [comment]
@topgun743 You need to rebuild subschema so that it can be used in the browser.  I have update my fork with it rebuilt use it with subschema-noreact.js.  

I have been adding view components for the form (Subschema.View).  

Also working on a fluent api to define the form schema based off C# classes, which is then converted to the subschema json which I will publish soon.

**Comment by topgun743** [comment]
Great @martosource. Good to know about your form schema work based off C# classes. OK as per my understanding I can use subschema if I add subschema-noreact.js. Right?

**Comment by jspears** [comment]
I've recently fixed the subschema build for no-react and updated to the latest version.   I don't use it so if either of you could let me know if you are having issues.


Also check out the Content component.   Now title's help, etc are all Content objects so they can do really smart stuff, and can help with getting the right wrapper nodes for your app.

**Comment by jspears** [comment]
Closing.
