### ISSUE TITLE
Compiled subschema.js not working when using with ReactJS

### ISSUE THREAD

**Issue by topgun743** [subschema/subschema#23]
I am using the ```subschema.js``` file (that I got from dist folder after building via webpack) in my HTML page head section along with ```react-with-addons.js```
When I execute my jsx code it gives me following error in firebug:
```prevComponentInstance is null```
But when I use ```subschema-noreact.js``` file, my jsx code works fine.

What am I missing? 
Do I have to use ```JSXTransformer.js``` in page with it or compile ```subschema.js``` with react-tools?

**Comment by jspears** [comment]
Afraid i don't use the compiled things, so I am pretty bad at guessing.

Make sure its react 0.13.x, make sure that is loaded before subschema.   Make sure you have the addons.

If you have an example or something, I could help more.

**Comment by topgun743** [comment]
I added react-with-addons.js to page header and yes its 0.13.x. Used subschema.js also in page header after that but it did not work out. Then used subschema-noreact.js and it works fine. Regarding example I will give it to you soon via some fiddle link.

**Comment by jspears** [comment]
Assuming this isn't an issue anymore.
