### ISSUE TITLE
Getting error after using current Subschema dist

### ISSUE THREAD

**Issue by topgun743** [subschema/subschema#26]
I am getting following error after I have updated to latest build of Subschema.
See the attached image please. My web page which was working before with the old code is not working anymore.

![ssbug](https://cloud.githubusercontent.com/assets/4273108/10864272/9ef2575a-800a-11e5-925c-f67498075fb9.png)

**Comment by jspears** [comment]
Yeah It's a bug in Babel a package change caused them it to break I will
have a work around shortly. Is this from git or from a npm install?

**Comment by topgun743** [comment]
I had updated my git repo today and then used:
`npm install`
and then 
`webpack`

**Comment by topgun743** [comment]
I am using Subschema in my live project and its awesome so far.
Will wait for your resolution of the bug mentioned above. Till then using old build. 
Thanks

**Comment by jspears** [comment]
This should be fixed with the latest released.

**Comment by topgun743** [comment]
ok thanks
