### ISSUE TITLE
React ES6 Class Notation

### ISSUE THREAD

**Issue by hairychris** [subschema/subschema#27]
Hey,

This is probably more of a mailing list thing, I tried to post but it didn't seem to come up. I've been trying to get this to work with ES6 class notation without much luck. Initially I was having problems with React 0.14 but that seems to work fine now if I use createClass notation.

The project I'm currently working on was built with ES6 notation, it seemed like a good idea at the time but it seems it is now incompatible with Subschema? I was looking through the code and saw there are a few mixins kicking around which means this won't work with ES6 notation without some manual intervention. 

I found the react-mixin library and react-mixin-decorator library (although the latter uses ES7) but I don't know how much work it is to go through and change things in Subschema.

Am I missing something?

Thanks a lot

**Comment by jspears** [comment]
Thanks, responded via mailing list, sorry your blocked by the spam filter.
