### ISSUE TITLE
How to design a custom UI?

### ISSUE THREAD

**Issue by topgun743** [subschema/subschema#28]
Due to a requirement, I am trying to use subschema to generate a long form with each form field having a checkbox coming against it.
But I cant figure out how to make it using subschema.
Please see the attached pic and guide me how is this UI possible using subschema? 
Thanks.
![customui](https://cloud.githubusercontent.com/assets/4273108/11274566/3cb4eabc-8efb-11e5-91c1-e4f592a4aea9.png)

**Comment by jspears** [comment]
So does the checkbox enable disable the car.
There is an easy and not so easy way.  The easier way is to add your own type.
```js

//Create a new type.
var {Select, Checkbox} = require('Subschema').types;
var CheckboxSelect = React.createClass({   
   mixins:[Subschema.FieldMixin],
    handleCheckChange(e){
      this.setState({checked:e.target.checked});
      if (!this.state.checked){
       //set the value to null if not checked.
       this.triggerChange(null);
     }
    },
    render(){
        return <div><input type="checked" checked={this.state.checked}  onChange={this.handleCheckChange}><Select {...this.props} disabled={this.state.checked}/></div> 
    }
});

loader.addType('CheckboxSelect', CheckboxSelect);

var schema = {
    mode:{
      type:'CheckboxSelect',
      options:['Car']
   },
    target:{
      type:'CheckboxSelect',
      title:'Target Version',
      options:['Current Version']
   }

} 
```

**Comment by jspears** [comment]
Hey I'm gonna close this, can you use the mailing list for future non defect related questions.   Trying to make that a little more useful. subschema@googlegroups.com

**Comment by topgun743** [comment]
Justin thanks for the answer.
CheckboxSelect is a great way to do this but unfortunately the HTML controls will all come through server returned json themselves.

Yes I created my custom type but for my scenario we cannot use this sort of approach:
```<Select {...this.props} disabled={this.state.checked}/>```

Instead I tried:
```<ObjectType {...this.props} disabled={this.state.checked} />```

but the enabling/disabling still did not occur on check/uncheck of corresponding checkboxes.

I then had to use jquery for making sure if the corresponding checkbox is selected, only then send the corresponding form field value to the server on submit. Though I think using jquery in this is a pathetic approach. May be you can suggest some better one.

And yes OK from next time I will post my help related queries on your mentioned google group. Thanks.

**Comment by topgun743** [comment]
ok I will try the FieldMixin and triggerChange approach. May be I was missing this. Will tell you about its outcome then.

**Comment by topgun743** [comment]
Didn't get my answer on this so far:
https://groups.google.com/forum/m/#!topic/subschema/dyag9pOIog4

**Comment by jspears** [comment]
I have this  example in a new version of subschema I am going to publish
monday.

https://github.com/jspears/subschema/blob/master/public/samples/Loader-setup.jsx

This won't work with the current version, but is pretty close.

**Comment by topgun743** [comment]
Yeah but again it is only based on Select control. While in my case the control against every checkbox will itself come from json, means it will by dynamic. So what about that?

**Comment by jspears** [comment]
Then you are better off using a template.

@template
class CheckboxTemplate extends React.Component {
    constructor(...rest) {
        super(...rest);
        //init state
        this.state = {disabled: false};
    }

    //inline styles, because this is an example
    render() {
        var {name, title, help, error, errorClassName, message,
fieldClass,  children} = this.props;
        if (!title) {
            title = ''
        }

        return (<div className={style.group+" " + (error != null ?
errorClassName || '' : '') + ' ' +  forEditor(this)}>
            <Content content={title} type="label"
className={style.label} htmlFor={name}/>

            <div className={title ? style.hasTitle : style.noTitle}>
                <Checkbox className='' style={{position: 'absolute',
left:'-5px', top:'5px'}}
                          onChange={(e)=>this.setState({disabled:
!e})} checked={!this.state.disabled}/>
                {children}
                {help === false ? null : <Content content={error ?
error : help} key='error-block' type='p'
                                                  className={error ?
style.error : style.help}/>}
            </div>
        </div>)
     }
}

schema:{
   model:{
      template:'CheckboxTemplate',
      type:'Select',
     options:'your options, here'
   }
}
