### ISSUE TITLE
Fix react-addons-css-transition-group dependency

### ISSUE THREAD

**Issue by brabeji** [subschema/subschema#32]
Hello @jspears, latest version `v0.50.6` seems to lack saved dependency on `react-addons-css-transition-group`.

Of all react form libraries, i like the API of subschema the most. Thumbs up, good job!

**Comment by jspears** [comment]
whoops, thanks. Hope it is useful.   Are you using it via webpack or via the compiled version.  It'll be fixed in a few minutes.

Thanks for letting me know.

**Comment by brabeji** [comment]
I am using modularized version via webpack.
