### ISSUE TITLE
I have an issue form submit function

### ISSUE THREAD

**Issue by Kikonejacob** [subschema/subschema#34]
Looking at the sample below, I hooked a function to handle form submit. When I click on cancel button the target of the click even is the form but when I click on submit button the target is the submit button object. How can I get the right target when I click on cancel button?

```javascript
(function () {
"use strict";
//uncomment these if you are using outside of the editor
//import React, {Component} from "react";
//import Subschema,{Form} from "Subschema";
            
var schema = {
	"schema": {
		"title": {
			"type": "Select",
			"options": [
				"Mr",
				"Mrs",
				"Ms"
			]
		},
		"name": {
			"type": "Text",
			"validators": [
				"required"
			]
		},
		"age": {
			"type": "Number"
		}
	},
	"fieldsets": [
		{
			"legend": "Name",
			"fields": "title, name, age",
			"buttons": [
				{
					"label": "Cancel",
					"action": "cancel",
					"buttonClass": "btn"
				},
				{
					"label": "Submit",
					"action": "submit",
					"buttonClass": "btn btn-primary"
				}
			]
		}
	]
};
var value = {};

function handleSubmit(e){

        e && e.preventDefault();
        debug.log(e);
}

return <Form schema={schema} value={value} onSubmit={handleSubmit} ><DisplayValueAndErrors/></Form>
}())
```

**Comment by jspears** [comment]
Try onButtonClick its second arg is the action

**Comment by Kikonejacob** [comment]
thank you for your answer. I will try that method.
Why is any button placed in the schema will invoke the onSubmit method when clicked ?
Anytime I click on the "cancel" button it  invoke the submit method.

**Comment by jspears** [comment]
.Because that's the way Dom works unfortunately.

**Comment by Kikonejacob** [comment]
Ok. I will use OnButtonClick to get the action of the button and store that value in document.pressed, then retrieve the value when OnSubmit is called. I'm assuming that OnButtonClick will trigger before OnSubmit
