### ISSUE TITLE
How do I disabled input or give default value to an input?

### ISSUE THREAD

**Issue by roadmanfong** [subschema/subschema#37]
Is there any API I can disable input or give default value without customizing new component?

**Comment by jspears** [comment]
If you pass a valueManager or a value in a form, you can give the default...

<Form value={stuff:'abc'} schema={stuff:'Text'}/>

As for disabled, you will need to use a conditional.   I need to write a
test to make sure it would work as expected.

-Justin

**Comment by roadmanfong** [comment]
thanks!
