### ISSUE TITLE
In resolver/fieldAttrs.js 'propKeys' shrinks

### ISSUE THREAD

**Issue by chaconnewu** [subschema/subschema#39]
This line of code:
https://github.com/subschema/subschema/blob/master/src/resolvers/fieldAttrs.js#L26 
will cause the propKeys to shrink by 1 even if the 'key' is not found. Because 'splice(-1, 1)' will trim the last item from the array.

**Comment by jspears** [comment]
ah,yes... thanks, will patch shortly.

**Comment by chaconnewu** [comment]
Thanks for the quick response @jspears ! Do you think dataType.js needs similar handling? Here: https://github.com/subschema/subschema/blob/master/src/resolvers/dataType.js#L16
