### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by pradoshs** [subschema/subschema#40]
Hi @jspears 
Awesome lib but I am struggling to get started with it, I am getting "Uncaught SyntaxError: Unexpected token import" in index.jsx on line 3 when it comes to importing the jsx files from here onwards `import _ReactCSSReplaceTransition from "./transition/ReactCSSReplaceTransition";`. I am not sure if it is not able to parse jsx, I have requisite babel loaders.
I have exhausted all options to fix it myself, any help would be much appreciated. 

Thanks

My package.json

```
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "repository": "",
  "scripts": {
    "start": "./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progess --inline --hot"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.9.1",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-runtime": "^6.9.2",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "lodash": "^4.13.1",
    "node-sass": "^3.7.0",
    "postcss-loader": "^0.9.1",
    "sass-loader": "^2.0.1",
    "style-loader": "^0.13.1",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1"
  },
  "peerDependencies": {
    "fbjs": "^0.8.0-alpha.3",
    "react-addons-css-transition-group": "^15.0.2",
    "subschema-prop-types": "*"
  },
  "dependencies": {
    "axios": "^0.12.0",
    "babel-preset-stage-1": "^6.5.0",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "react-jsonschema-form": "^0.33.0",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.1",
    "redux": "^3.5.2",
    "redux-promise": "^0.5.3"
  }
}

```

My webpack.config.js 

``` javascript
var webpack = require("webpack");
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const path = require('path');

const sassLoaders = [
  'css-loader',
  'postcss-loader',
  'sass-loader?indentedSyntax=sass&includePaths[]=' + path.resolve(__dirname, './src')
];

module.exports = {
  devtool: 'source-map',
  entry: [
    './src/index.js'
  ],
  output: {
    path: __dirname,
    publicPath: '/',
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      {
        test: /.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel',
        include: __dirname
      },
      {
        test: /\.sass$/,
        loader: ExtractTextPlugin.extract('style-loader', sassLoaders.join('!'))
      }
    ]
  },
  plugins: [
    new webpack.IgnorePlugin(/^(buffertools)$/), // unwanted "deeper" dependency,
    new ExtractTextPlugin('style.css')
  ],
  resolve: {
    extensions: ['', '.js', '.jsx', 'sass'],
    root: [path.join(__dirname, './src')]
  },
  devServer: {
    historyApiFallback: true,
    contentBase: './'
  }
};

```

Got these for .babelrc

```
{
  "presets": ["react", "es2015-loose", "es2015", "stage-0", "react-hmre"]
}
```

**Comment by jspears** [comment]
So ... it looks like you've excluded node_modules from the babel transformer.  I would guess you are requiring a subschema component directly rather than dereferencing the subchema import.  So webpack will try to load that single file.  It fails because it needs to be transpiled but node_modules are excluded.   

Easy fix, is to add 
```js
{
 test:/\.jsx?$/,
  exclude:/node_modules/,
  include:/node_modules\/subschema/
  loader:'babel'
...
}
```
Or you can you include subschema like this, witch *should* resolve to subschema/dist/subschema-noreact.js but it can very see the subschema package.json and the webpack package resolution for more details.
```js
import {Form} from 'subschema';
```

**Comment by pradoshs** [comment]
@jspears adding ```include:/node_modules\/subschema/``` didn't make any difference. 
I am using ```import {Form} from 'subschema';``` in my component.

**Comment by jspears** [comment]
Did you figure this out?   Sorry, I lost the thread.

**Comment by mrarlloyd** [comment]
I'm suffering with this too, I'm wondering if it's todo with OS Case sensitivity, i'm developing on Windows....

When i try 
`import {Form} from 'Subschema';`
The error i get is:
`Module not found: [CaseSensitivePathsPlugin] '{PROJECT_PATH}\node_modules\Subschema\src\index.jsx' does not match the corresponding path on disk 'subschema'.`
however, if i try:
`import {Form} from 'subschema';`
I get the error reported above.

With a lowercase 'subschema' it tries to load */subschema/src/index.jsx*

**Comment by jspears** [comment]
Almost garuntee its case sensitivety.   I  have never seen Subschema in node_modules before.  Did you npm install it?

**Comment by mrarlloyd** [comment]
Ah, that's interesting. No, the folder itself is definitely [s]ubschema, from npm install. But,
`import {Form} from 'Subschema';`
generates that error with the case issue... `does not match the corresponding path on disk 'subschema'.` 

I'm using create-react-app & react-scripts, in it's standard config, so don't have anything specific in webpack or babel configs at the mo.

I'll try fudging it in using just the /dist folder, and see where i get to .

**Comment by jspears** [comment]
Ahh there you go you need an alias in webpack for that.  I set a project a while ago, that used the react-setup stuff to see how its done, but now can't find it.    Basically
webpack.config.js and adding the stuff that subschema needs
```
webpack.resolve.alias[ 'Subschema'] = join('node_modules/subschema/dist/subschema-noreact.js');
```

I have my own quickstart thing not as good. I will try to make subschema more quick start friendly in the next release.
