### ISSUE TITLE
[FR] Input range

### ISSUE THREAD

**Issue by alexandernst** [subschema/subschema#43]
It would be nice if this library had support for an input range component. (Which is supported by all browsers, IE9+)

Or maybe just create a new repository with "extra" components and start adding there more advanced components.

**Comment by jspears** [comment]
you should be able to use a text field with a {type:"Text", dataType:"range"}

**Comment by alexandernst** [comment]
I just tried that, but it's not working.

**Comment by jspears** [comment]
"age": {
      "type": "Text",
      "fieldAttrs": {
        "type": "range"
      }
    }
