### ISSUE TITLE
React 15.2.1 issue a warning about unknown props passed to DOM elements

### ISSUE THREAD

**Issue by kikonejacob** [subschema/subschema#45]
React 15.2.1 issue a warning about unknown props passed to DOM elements as state in the documentation: https://fb.me/react-unknown-prop . I have review subschema code and found that the following module was passing {...props} to the DOM elements. some props which does not belongs to standard DOM form props   may then be passed to the DOM form elements and therefore create the warning.

subschema/src/templates/FormTemplate.jsx

``` javascript
 render() {
        const {children, style, fieldAttrs, formClass, className, ...props} = this.props;
        return (<form {...props} className={className || formClass} {...fieldAttrs}>
            {children}
        </form>);
    }
```

**Comment by kiranvenkatesh** [comment]
app.js:1485 Warning: Unknown prop `formClassClass` on <form> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in form
    in FormTemplate
    in FormTemplate$Wrapper$5b8cd857
    in RenderTemplate
    in e
    in e$Wrapper$7a0
    in Form (created by Login)
    in div (created by Login)
    in Login

AND

app.js:1485 Warning: Unknown prop `validators` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in input
    in Text
    in Text$Wrapper$-6706cb50
    in div
    in div
    in EditorTemplate
    in EditorTemplate$Wrapper$5b8cd857
    in RenderTemplate
    in Field
    in Field$Wrapper$7a0
    in fieldset
    in FieldSetTemplate
    in FieldSetTemplate$Wrapper$5b8cd857
    in RenderTemplate
    in FieldSet
    in FieldSet$Wrapper$7a0
    in form
    in FormTemplate
    in FormTemplate$Wrapper$5b8cd857
    in RenderTemplate
    in e
    in e$Wrapper$7a0
    in Form (created by Login)
    in div (created by Login)
    in Login

**Comment by alexandernst** [comment]
I can confirm this as I'm getting it also.

**Comment by kiranvenkatesh** [comment]
A workaround could be to create your own template as an override using the addType function.

loader.addType( "Text", CustomText );

**Comment by jspears** [comment]
Shouldn't be hard to fix.   validators shouldn't be getting passed down, hopefully have a release tomorrow.  Thanks for the issue report.

**Comment by alexandernst** [comment]
Can I help with something so we can get a release fixing this bug asap?

**Comment by speajus2** [comment]
A PR would totally speed it up. Been busier than expected.

**Comment by alexandernst** [comment]
Do you have any release scripts I can use? Do you want to merge something before the PR?

**Comment by jspears** [comment]
I think I fixed these in last release.
