### ISSUE TITLE
Dependant inputs

### ISSUE THREAD

**Issue by alexandernst** [subschema/subschema#47]
I have a very complex form like this one: https://jsbin.com/hojoxavixe/2/edit?html,js,output

As you can see, the first dropdown lets the user select the type of configuration. Just for the sake of this example, lets pretend there will be only 2 options: `Single` and `Front + backend`. Anyways, in my app there could be multiple options.

If `Single` is selected, then only 1 `Tier` component is rendered (1 dropdown + 1 set of options + 1 slider). If `Front + backend` is selected, 2 `Tier` components are rendered. Each option (`Single`, `Front + backend`, etc..) can have from 1 to N `Tier` components.

Each `Tier` component is independent of the rest, so, for example, `Front + backend` could have a `m1.micro` at the `Front` and a `m2.micro` at the `Backend`.

Given all that information, my question is: is there a way (and if "yes", how) to make the `Type`, the `Disk Type` and the `Disk Size` elements of each `Tier` to depend on themselves in chain.

For example, if `m1.micro` is selected, only `Magnetic` disks should be allowed, from 10 to 80GB. But if `m2.micro` is selected, both `SSD` and `Magnetic` disks should be allowed. If `SSD` is selected, sizes from 10 to 40GB should be allowed, if `Magnetic` is selected, allow disks from 40 to 100GB.

Any ideas or tips how to implement that?

**Comment by jspears** [comment]
So you could "listen" to the other property

```jsx
import {PropTypes, types} from 'Subschema';
import Range from '...';
export class DiskInfo {
   static propTypes = {
             diskType:PropTypes.value <-- this is makes the magic work diskType will be kept in sync,
   }
  static defaultProps = {
     diskType:"../diskType"<-- this will listen to the change of diskType and any time that changes
 }

 render(){
   const {diskType, ...props} = this.props;
   if (diskType == 'mag')
     return <Range {...props} max={80} min={1}/>
 }
...rest here

} 




```

**Comment by alexandernst** [comment]
So, this answers the second part of my question. What about the first one? How can I make the second select depend on the first one?

**Comment by alexandernst** [comment]
This is what my final goal looks like:

    "tierSingle": {
      "type": "Object",
      "subSchema": {
        "type": {
          "type": "Select",
          "options": [
            {'label': 'SSDs', 'val': {'val': 'ssd', 'opts': ['SSD 1', 'SSD 2']}},
            {'label': 'Magnetics', 'val': {'val': 'magnetics', 'opts': ['HDD 1', 'HDD 2']}},
          ]
        },
        "diskType": {
          "type": "SelectListen",
          "options": "tierSingle.type.opts"  <--- when "type" is "SSDs", this will be ['SSD 1', 'SSD 2']
        },
        "diskSize": {
          "type": "Range",
          "min": 8
        }
      }
    }


Is something like that possible?

**Comment by speajus2** [comment]
Yes,  I think I have some examples of that... but basically.

```jsx

export class SelectListen extends Component {
//This will make options resolve to the path  
 static defaultProps = {...Select.defaultProps, options:PropTypes.value}

  render(){
    return <Select {...this.props}/>
  }  

}

```

**Comment by alexandernst** [comment]
It doesn't seem to work. What would be the exact path I should use, given as example the code I pasted in my last comment?

**Comment by jspears** [comment]
Taken from 
http://subschema.github.io/subschema/#/ListenerProperty

Note this expects the options to be stored in 
{
 label, val
}
format. 


```jsx
class SelectListen extends React.Component {
    static propTypes = {
        ...Select.propTypes,
        options:PropTypes.listener

    };

    render() {
        var value = this.props.value;
        if (value == null && this.props.options) {
           //this.props.options should be normalized to {label,val} format.
            value = this.props.options[0].val;
        }
       //this.props.options should be normalized to {label,val} format.
        return <Select {...this.props} value={value}/>
    }
}
```

**Comment by alexandernst** [comment]
I was asking about the path. What should I put in the path, e.g:

    "diskType": {
      "type": "SelectListen",
      "options": "tierSingle.type.opts"  <---- path
    },

Maybe `./type.opts`? Or `./type`?

**Comment by alexandernst** [comment]
Ok, the path is `tierSingle.type` (I found out by using the ValueManager and listening to the change event of `type` and then printing the `path`), but I'm still getting `Failed prop type: SelectListen: prop type `options` is invalid; it must be a function, usually from React.PropTypes.`. 

Any ideas?

**Comment by alexandernst** [comment]
Hey! I'm sorry for insisting so much, but this is really important for me. I was thinking about the problem and I figured out I might want to do something else. Is it possible to inspect (programmatically) all the values from the entire form?

**Comment by alexandernst** [comment]
Oh, I just saw that there is `vm.getValue()`. That should help me do what I want.
