### ISSUE TITLE
Lodash version

### ISSUE THREAD

**Issue by Angelmmiguel** [subschema/subschema#50]
Hello!

We are using `subschema` in a project. The version of `lodash` library is `ˆ3.0.1`. Is there a reason to use this version of that library? The last version is `4.15.0`. npm are showing us several problems of `UNMET PEER DEPENDENCY`.

I was preparing a pull request to update it but I saw that related projects like `subschema-expressions` have that dependency too. So before start to fork several project, I prefer to ask you.

Thanks!

**Comment by jspears** [comment]
Have no real reason for not going to lodash 4, except it was a bunch of work.   Be more than happy to merge PRs.   subschema-expression, subschema-injection, subschema-demo, subschema-test-support, subschema-project will need to be updated.   You can get them all from a recursive checkout of subschema-devel.

**Comment by Angelmmiguel** [comment]
Thanks you @jspears for your response. Yes, I'm going to check lodash 4 changelog because it includes a lot breaking changes.
